# qr.py — XPLØR QR (kiosk mode: ONLY shows data received via ?data=)
import streamlit as st
import urllib.parse
import json
import base64

st.set_page_config(page_title="XPLØR QR", page_icon="", layout="centered")

# ====== Styles ======
st.markdown("""
<style>
html, body, [class*="css"] {
  background: linear-gradient(135deg, #e0f7fa, #ffffff);
  font-family: 'Segoe UI', sans-serif; color: #2c3e50;
}
h1, h3 { text-align: center; color: #0a5f78; }
.xplor-button {
  display:block; width:100%;
  background: linear-gradient(135deg, #009688, #4db6ac);
  color:white !important; padding:16px; margin:12px 0;
  border:none; border-radius:30px; font-size:18px; font-weight:600;
  text-align:center; transition: all .3s ease; text-decoration:none;
  box-shadow: 0 6px 16px rgba(0,0,0,0.1);
}
.xplor-button:hover { background: linear-gradient(135deg, #00796b, #26a69a); transform: scale(1.07); cursor:pointer; }
.footer { text-align:center; margin-top:32px; opacity:.7; }
.badge { display:inline-block; background:#e0f2f1; color:#00695c; padding:6px 12px; border-radius:999px; margin:4px; font-size:14px; }
.cta-link { text-align:center; margin-top: 24px; }
.cta-link a { color:#00695c; font-weight:600; text-decoration:underline; }
</style>
""", unsafe_allow_html=True)

# ====== Utility: decode ?data= (base64 url-safe) ======
def _decode_data_param(data_param: str):
    try:
        padding = "=" * (-len(data_param) % 4)  # complete padding if missing
        raw = base64.urlsafe_b64decode(data_param + padding).decode("utf-8")
        return json.loads(raw)
    except Exception:
        return None

# ====== Read parameters ======
params = st.query_params  # New Streamlit API
data_param = params.get("data")  # str | None

# ====== Reusable block: Web CTA ======
def render_cta_web():
    st.markdown(
        "<div class='cta-link'>For more information, visit the page at "
        "<a href='http://www.xplorandplay.com/' target='_blank' rel='noopener noreferrer'>http://www.xplorandplay.com/</a>"
        "</div>",
        unsafe_allow_html=True
    )
    # (If you don't want an additional button, remove this block)
    st.markdown(
        "<a class='xplor-button' href='http://www.xplorandplay.com/' target='_blank' rel='noopener noreferrer'>Go to xplorandplay.com</a>",
        unsafe_allow_html=True
    )

# ====== Direct flow with ?data= ======
if data_param:
    payload = _decode_data_param(data_param)
    if not payload:
        st.error("Couldn't read QR data. Ask the robot to generate a new one.")
        render_cta_web()
        st.markdown("<div class='footer'>@Xplor.pty © 2025</div>", unsafe_allow_html=True)
        st.stop()

    nombre       = payload.get("nombre", "")
    pais         = payload.get("pais", "")
    email        = payload.get("email", "")
    categoria    = payload.get("categoria", "")
    subcategoria = payload.get("subcategoria", "")
    sugerencias  = payload.get("sugerencias", [])

    # Header
    if nombre or pais:
        st.markdown(f"<h1>Hello {nombre.title()} from {pais.title()}!</h1>", unsafe_allow_html=True)
    else:
        st.markdown("<h1>XPLØR Your recommendations </h1>", unsafe_allow_html=True)
    if email:
        st.markdown(f"<h3>Email: {email}</h3>", unsafe_allow_html=True)

    # Chips
    chips = []
    if categoria: chips.append(f"<span class='badge'>Category: {categoria}</span>")
    if subcategoria: chips.append(f"<span class='badge'>Interest: {subcategoria}</span>")
    if chips:
        st.markdown(" ".join(chips), unsafe_allow_html=True)

    # Suggestions -> now link to xplorandplay.com/explore.html?q=<place>
    if sugerencias:
        st.markdown("### We recommend:")
        for lugar in sugerencias:
            dest = f"http://www.xplorandplay.com/explore.html?q={urllib.parse.quote(lugar)}"
            st.markdown(
                f"<a class='xplor-button' href='{dest}' target='_blank' rel='noopener noreferrer'>{lugar}</a>",
                unsafe_allow_html=True
            )
    else:
        st.info("There are no suggestions yet. Ask the robot to recommend 3–5 places.")

    # CTA to the site
    render_cta_web()

    st.markdown("<div class='footer'>@Xplor.pty © 2025</div>", unsafe_allow_html=True)
    st.stop()

# ====== Kiosk mode: if ?data= is NOT present, there is no form ======
st.markdown("<h1>Scan the robot's QR</h1>", unsafe_allow_html=True)
st.write("Open this page from the QR code generated by XPLØRBot to see your recommendations.")
render_cta_web()
st.markdown("<div class='footer'>XPLØR © 2025</div>", unsafe_allow_html=True)
