import streamlit as st
import urllib.parse
import json, base64

st.set_page_config(page_title="XPLØR QR", page_icon="🌐", layout="wide")

# 🌈 NEON FUTURISTIC STYLE — Designed for WRO Stage Display
st.markdown("""
<style>
html, body, [class*="css"] {
    background: radial-gradient(circle at 20% 30%, #e3f2fd, #ffffff 70%);
    font-family: 'Segoe UI', sans-serif;
    color: #0d1b2a;
}
h1 {
    text-align: center;
    font-size: 64px;
    font-weight: 900;
    background: linear-gradient(90deg, #0288d1, #00e5ff, #0288d1);
    -webkit-background-clip: text;
    -webkit-text-fill-color: transparent;
    text-shadow: 0 0 20px rgba(0, 230, 255, 0.5);
    margin-top: 20px;
    letter-spacing: 2px;
    animation: glow 3s infinite alternate;
}
@keyframes glow {
    from { text-shadow: 0 0 15px rgba(0,230,255,0.3); }
    to { text-shadow: 0 0 30px rgba(0,230,255,0.7); }
}
h3, h4 {
    text-align: center;
    color: #01579b;
    font-weight: 600;
}
.divider {
    height: 4px;
    width: 100px;
    background: linear-gradient(90deg, #0288d1, #00e5ff);
    margin: 25px auto;
    border-radius: 2px;
    box-shadow: 0 0 12px rgba(0,229,255,0.4);
}
.xplor-button {
    display: block;
    width: 100%;
    background: linear-gradient(135deg, #0288D1, #00BCD4);
    color: white !important;
    padding: 22px;
    margin: 16px 0;
    border: none;
    border-radius: 50px;
    font-size: 22px;
    font-weight: 700;
    letter-spacing: 0.7px;
    text-align: center;
    transition: all 0.35s ease;
    text-decoration: none;
    box-shadow: 0 8px 25px rgba(0,0,0,0.25);
}
.xplor-button:hover {
    background: linear-gradient(135deg, #00e5ff, #0288d1);
    transform: scale(1.08);
    box-shadow: 0 12px 35px rgba(0,0,0,0.35);
}
.fade-in {
    animation: fadeIn 1.4s ease-in;
}
@keyframes fadeIn {
    from {opacity: 0; transform: translateY(20px);}
    to {opacity: 1; transform: translateY(0); opacity: 1;}
}
.footer {
    text-align: center;
    color: #37474f;
    margin-top: 60px;
    font-size: 16px;
    letter-spacing: 0.3px;
}
.flag {
    width: 28px;
    vertical-align: middle;
    margin-left: 6px;
}
</style>
""", unsafe_allow_html=True)

# ✅ Updated Streamlit method for 2025 compatibility
params = st.query_params
payload_data = params.get("data", None)

# 🧩 Decode robot payload
if payload_data:
    try:
        padded = payload_data + "=" * (-len(payload_data) % 4)
        decoded = json.loads(base64.urlsafe_b64decode(padded.encode()).decode())

        category = decoded.get("category", "Tourist attractions")
        subcategory = decoded.get("subcategory", "")
        suggestions = decoded.get("suggestions", [])
    except Exception:
        st.error("⚠️ Invalid QR data. Please scan again.")
        st.stop()
else:
    st.warning("⚠️ Please scan the QR code generated by XPLØRBOT to view your recommendations.")
    st.stop()

# 🧭 Same data as the robot
SUGGESTIONS = {
    "Museums": ["Biomuseum", "Canal Museum", "Museum of Contemporary Art"],
    "Restaurants": ["Seafood Market", "Tantalo", "Maito", "Fonda Lo Que Hay"],
    "Nature": ["Metropolitan Park", "Taboga Island", "Coiba National Park", "Boquete"],
    "Shopping malls": ["Multiplaza", "Albrook Mall", "Metromall", "Soho Mall"],
    "Budget": ["Hostel Loco Coco Loco", "Hotel Centroamericano", "Hotel Marparaiso"],
    "Luxury": ["Hotel Las Américas", "W Panama", "Trump Tower"],
    "Downtown": ["Hotel El Panamá", "Hotel Riu", "Hotel Marbella"],
    "With pool": ["Sortis Hotel", "Hotel Crowne Plaza", "Bristol Panama"],
    "Taxi": ["Uber", "Cabify", "Panamanian Taxis"],
    "Metro": ["Line 1", "Line 2", "MetroBus Recharges"],
    "Car rental": ["Thrifty", "Hertz", "Dollar Rent A Car"],
    "Ride-sharing apps": ["Uber", "InDrive", "Cabify"],
    "Hospital": ["Punta Pacífica Hospital", "National Hospital", "Santo Tomás Hospital"],
    "Police": ["National Police", "DIJ", "Emergency 104"],
    "Embassy": ["US Embassy", "French Embassy", "Colombian Embassy"],
    "Pharmacy": ["Arrocha", "Metro Plus", "El Javillo"]
}

# 🖥️ HEADER
st.markdown("<h1 class='fade-in'>XPLØRBOT</h1>", unsafe_allow_html=True)
st.markdown("<div class='divider'></div>", unsafe_allow_html=True)
st.markdown(f"<h3>Welcome to Panama</h3>", unsafe_allow_html=True)
st.markdown(f"<h4>Category: <b>{category}</b></h4>", unsafe_allow_html=True)
if subcategory:
    st.markdown(f"<h4>Topic: <b>{subcategory}</b></h4>", unsafe_allow_html=True)
st.markdown("<div class='divider'></div>", unsafe_allow_html=True)

# 🌟 RECOMMENDATIONS — All buttons lead to your explore page
if suggestions:
    st.markdown("<h3 class='fade-in'>Recommended Places</h3>", unsafe_allow_html=True)
    for place in suggestions:
        st.markdown(
            f"<a class='xplor-button fade-in' href='https://www.xplorandplay.com/explore.html' target='_blank'>{place}</a>",
            unsafe_allow_html=True)
else:
    fallback = SUGGESTIONS.get(subcategory, [])
    if fallback:
        st.markdown("<h3 class='fade-in'>Recommended Places</h3>", unsafe_allow_html=True)
        for place in fallback:
            st.markdown(
                f"<a class='xplor-button fade-in' href='https://www.xplorandplay.com/explore.html' target='_blank'>{place}</a>",
                unsafe_allow_html=True)
    else:
        st.info("No recommendations available. Please rescan your QR.")

# 🌍 FOOTER
st.markdown("""
<div class='footer'>
    XPLØR © 2025 – Made in Panama 
    <img class='flag' src='https://upload.wikimedia.org/wikipedia/commons/a/ab/Flag_of_Panama.svg'>
</div>
""", unsafe_allow_html=True)
